config/routes.rb
Rails.application.routes.draw do

#Casein routes
namespace :casein do
    resources :dishes
    resources :menus
    resources :restaurants
    resources :events
end

  devise_for :users
  mount Attachinary::Engine => "/attachinary"
  get "home", to: "pages#home"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  end

  scope '(:locale)', locale: /en|ar/ do
    get "home", to: "pages#home"
    root to: 'pages#home'
    resources :users do
      resources :restaurants
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/casein/dishes_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class DishesController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Dishes'
      @dishes = Dish.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View dish'
      @dish = Dish.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new dish'
      @dish = Dish.new
    end

    def create
      @dish = Dish.new dish_params

      if @dish.save
        flash[:notice] = 'Dish created'
        redirect_to casein_dishes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new dish'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update dish'

      @dish = Dish.find params[:id]

      if @dish.update_attributes dish_params
        flash[:notice] = 'Dish has been updated'
        redirect_to casein_dishes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this dish'
        render action: :show
      end
    end

    def destroy
      @dish = Dish.find params[:id]

      @dish.destroy
      flash[:notice] = 'Dish has been deleted'
      redirect_to casein_dishes_path
    end

    private

    def dish_params
      params.require(:dish).permit(:name, :description)
    end
  end
end

app/controllers/casein/events_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class EventsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Events'
      @events = Event.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View event'
      @event = Event.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new event'
      @event = Event.new
    end

    def create
      @event = Event.new event_params

      if @event.save
        flash[:notice] = 'Event created'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new event'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update event'

      @event = Event.find params[:id]

      if @event.update_attributes event_params
        flash[:notice] = 'Event has been updated'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to update this event'
        render action: :show
      end
    end

    def destroy
      @event = Event.find params[:id]

      @event.destroy
      flash[:notice] = 'Event has been deleted'
      redirect_to casein_events_path
    end

    private

    def event_params
      params.require(:event).permit(:name, :date, :time, :description)
    end
  end
end

app/controllers/casein/menus_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class MenusController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Menus'
      @menus = Menu.order(sort_order(:dish_id)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View menu'
      @menu = Menu.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new menu'
      @menu = Menu.new
    end

    def create
      @menu = Menu.new menu_params

      if @menu.save
        flash[:notice] = 'Menu created'
        redirect_to casein_menus_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new menu'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update menu'

      @menu = Menu.find params[:id]

      if @menu.update_attributes menu_params
        flash[:notice] = 'Menu has been updated'
        redirect_to casein_menus_path
      else
        flash.now[:warning] = 'There were problems when trying to update this menu'
        render action: :show
      end
    end

    def destroy
      @menu = Menu.find params[:id]

      @menu.destroy
      flash[:notice] = 'Menu has been deleted'
      redirect_to casein_menus_path
    end

    private

    def menu_params
      params.require(:menu).permit(:dish_id, :restaurant_id)
    end
  end
end

app/controllers/casein/restaurants_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class RestaurantsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Restaurants'
      @restaurants = Restaurant.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View restaurant'
      @restaurant = Restaurant.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new restaurant'
      @restaurant = Restaurant.new
    end

    def create
      @restaurant = Restaurant.new restaurant_params

      if @restaurant.save
        flash[:notice] = 'Restaurant created'
        redirect_to casein_restaurants_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new restaurant'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update restaurant'

      @restaurant = Restaurant.find params[:id]

      if @restaurant.update_attributes restaurant_params
        flash[:notice] = 'Restaurant has been updated'
        redirect_to casein_restaurants_path
      else
        flash.now[:warning] = 'There were problems when trying to update this restaurant'
        render action: :show
      end
    end

    def destroy
      @restaurant = Restaurant.find params[:id]

      @restaurant.destroy
      flash[:notice] = 'Restaurant has been deleted'
      redirect_to casein_restaurants_path
    end

    private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :time)
    end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :casein, action: :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

     # A list of stylesheets to include in the authentication layout. Do not remove the core casein/login, but you can change the load order, if required.
    def casein_config_auth_stylesheet_includes
      %w[casein/login casein/auth_custom]
    end
  
    # A list of JavaScript files to includein the authentication layout. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_auth_javascript_includes
      %w[casein/casein casein/auth_custom]
    end
    
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/casein/events/_form.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<% I18n.locale = :en %>
<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :name %>
  </div>
  <div class="col-lg-6">
    <%= casein_date_select f, f.object, :date %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_time_select f, f.object, :time %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_area f, f.object, :description %>
  </div>
</div>

app/views/casein/events/_table.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th><%= casein_sort_link "Name", :name %></th>
      <th><%= casein_sort_link "Date", :date %></th>
      <th><%= casein_sort_link "Time", :time %></th>
      <th><%= casein_sort_link "Description", :description %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <% events.each do |event| %>
    <tr>
      <td><%= casein_table_cell_link event.name, casein_event_path(event) %></td>
      <td><%= casein_table_cell_link event.date, casein_event_path(event) %></td>
      <td><%= casein_table_cell_link event.time, casein_event_path(event) %></td>
      <td><%= casein_table_cell_link event.description, casein_event_path(event) %></td>
      <td class="delete">
        <%= link_to(casein_show_row_icon("trash"), casein_event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete this event?" }) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/casein/events/index.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Events<%= casein_pagination_details @events %></h2>

<%= render partial: 'casein/events/table', locals: { events: @events } %>

<div class="text-center">
  <%= will_paginate @events %>
</div>

<%= content_for :sidebar do %>

  <li><%= link_to "#{casein_show_icon "plus-sign"}Add a new event".html_safe, new_casein_event_path %></li>

<% end %>

app/views/casein/events/new.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Add a new event</h2>

<%= form_for @event, url: casein_events_path do |f| %>
  <!-- Changing the locale so to fix the date-picker error -->
  <% I18n.locale = :en %>
  <%= render partial: 'casein/events/form', locals: { f: f } %>

  <p class="submits">
    <%= link_to 'Cancel', casein_events_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Add new event", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_events_path %></li>
<% end %>

app/views/casein/events/show.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>View event</h2>

<%= form_for @event, url: casein_event_path(@event) do |f| %>

  <%= render partial: 'casein/events/form', locals: { f: f } %>

  <p class="submits">
      <%= link_to 'Cancel', casein_events_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Save changes", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_events_path %></li>
<% end %>