config/routes.rb
Rails.application.routes.draw do

#Casein routes
namespace :casein do
    resources :dishes
    resources :menus
    resources :restaurants
    resources :events
end

  devise_for :users
  mount Attachinary::Engine => "/attachinary"
  get "home", to: "pages#home"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  end

  scope '(:locale)', locale: /en|ar/ do
    get "home", to: "pages#home"
    root to: 'pages#home'
    resources :users do
      resources :restaurants
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :restaurants, through: :menus
  has_many :menus
end

app/controllers/casein/dishes_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class DishesController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Dishes'
      @dishes = Dish.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View dish'
      @dish = Dish.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new dish'
      @dish = Dish.new
    end

    def create
      @dish = Dish.new dish_params

      if @dish.save
        flash[:notice] = 'Dish created'
        redirect_to casein_dishes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new dish'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update dish'

      @dish = Dish.find params[:id]

      if @dish.update_attributes dish_params
        flash[:notice] = 'Dish has been updated'
        redirect_to casein_dishes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this dish'
        render action: :show
      end
    end

    def destroy
      @dish = Dish.find params[:id]

      @dish.destroy
      flash[:notice] = 'Dish has been deleted'
      redirect_to casein_dishes_path
    end

    private

    def dish_params
      params.require(:dish).permit(:name, :description)
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      redirect_to @dish, notice: 'Dish was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dishes/1
  def update

    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Dish was successfully updated.'
    else
      render :edit
    end

  end

  # DELETE /dishes/1
  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: 'Dish was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :description)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= simple_form_for(@dish) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>