config/routes.rb
Rails.application.routes.draw do

#Casein routes
namespace :casein do
    resources :dishes
    resources :menus
    resources :restaurants
    resources :events
end

  devise_for :users
  mount Attachinary::Engine => "/attachinary"
  get "home", to: "pages#home"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  end

  scope '(:locale)', locale: /en|ar/ do
    get "home", to: "pages#home"
    root to: 'pages#home'
    resources :users do
      resources :restaurants
    end
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :events
  has_many :dishes, through: :menus
  has_many :menus
  has_many :users
end

app/controllers/casein/restaurants_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class RestaurantsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Restaurants'
      @restaurants = Restaurant.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View restaurant'
      @restaurant = Restaurant.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new restaurant'
      @restaurant = Restaurant.new
    end

    def create
      @restaurant = Restaurant.new restaurant_params

      if @restaurant.save
        flash[:notice] = 'Restaurant created'
        redirect_to casein_restaurants_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new restaurant'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update restaurant'

      @restaurant = Restaurant.find params[:id]

      if @restaurant.update_attributes restaurant_params
        flash[:notice] = 'Restaurant has been updated'
        redirect_to casein_restaurants_path
      else
        flash.now[:warning] = 'There were problems when trying to update this restaurant'
        render action: :show
      end
    end

    def destroy
      @restaurant = Restaurant.find params[:id]

      @restaurant.destroy
      flash[:notice] = 'Restaurant has been deleted'
      redirect_to casein_restaurants_path
    end

    private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number)
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>